[package]
name = "bevy_pixels"
description = "Bevy plugin that uses Pixels (a tiny pixel buffer) for rendering"
version = "0.2.0"
authors = ["David Cristofaro <david@dtcristo.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/dtcristo/bevy_pixels"
keywords = ["bevy", "pixels", "graphics", "2d", "framebuffer"]
categories = ["game-engines", "graphics", "rendering"]
exclude = ["images/**/*"]
resolver = "2"

[dependencies]
bevy_app = "0.5"
bevy_diagnostic = "0.5"
bevy_ecs = "0.5"
bevy_window = "0.5"
bevy_winit = "0.5"
pixels = "0.8"

[dev-dependencies]
bevy_internal = { version = "0.5", features = ["bevy_winit"] }
rand = "0.8"

[features]
default = ["x11"]
x11 = ["bevy_winit/x11"]
wayland = ["bevy_winit/wayland"]
