name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
        include:
        - os: ubuntu
          extra: --features x11
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
    - name: Clippy
      uses: actions-rs/clippy-check@v1.0.7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
  build:
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
        include:
          - os: ubuntu
            extra: --features x11
            name: -x11
          - os: ubuntu
            extra: --features wayland
            name: -wayland
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release ${{ matrix.extra }} --example minimal
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: build-${{ matrix.os }}${{ matrix.name }}
        path: target/release/examples/minimal
