name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
        include:
        - os: ubuntu
          extra: --features x11
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
    - name: Clippy
      uses: actions-rs/clippy-check@v1.0.7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
  test:
    strategy:
      matrix:
        os: [ubuntu, windows] # TODO: figure out how to enable a virtual display server for macOS
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run headless test
      uses: GabrielBB/xvfb-action@v1
      with:
        run: cargo run ${{ matrix.extra }} --example ci
